# Generated by Django 6.0.3 on 2026-03-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_application_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(default='Backend Developer', max_length=100, unique=True),
        ),
    ]
