# Generated by Django 6.0.3 on 2026-03-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='logo',
            field=models.ImageField(blank=True, default='company_logos/default_avatar.png', null=True, upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='Profile_pics/'),
        ),
    ]
