# Generated by Django 6.0.3 on 2026-03-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_alter_employerprofile_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='logo',
            new_name='avatar',
        ),
    ]
